"""Export ASCII art to TXT and HTML files."""
from __future__ import annotations

import html
from pathlib import Path

from api import Character
from settings import settings
from utils import EXPORTS_DIR


def _filename(char: Character, ext: str) -> Path:
    safe_name = char.name.lower().replace(" ", "_").replace("/", "-")
    return EXPORTS_DIR / f"{safe_name}_{char.id}.{ext}"


def export_txt(char: Character, ascii_art: str) -> Path:
    """Write plain text file; return the path."""
    path = _filename(char, "txt")
    lines = [
        f"Rick Terminal Export — {char.name}",
        "=" * 60,
        f"ID:       {char.id}",
        f"Status:   {char.status}",
        f"Species:  {char.species}",
        f"Gender:   {char.gender}",
        f"Origin:   {char.origin}",
        f"Location: {char.location}",
        f"Episodes: {char.episode_count}",
        "=" * 60,
        "",
        ascii_art,
    ]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def export_html(char: Character, ascii_art: str) -> Path:
    """Write a self-contained HTML page with monospace font."""
    path = _filename(char, "html")
    color = settings.color_theme
    escaped_art = html.escape(ascii_art)

    bg_css = "background:#0a0a0a"
    fg_css = f"color:{color}"

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Rick Terminal — {html.escape(char.name)}</title>
  <style>
    body {{ {bg_css}; {fg_css}; font-family: 'Courier New', Courier, monospace;
           margin: 0; padding: 2rem; }}
    h1   {{ color: #ffffff; border-bottom: 1px solid {color}; padding-bottom:.5rem; }}
    table {{ border-collapse: collapse; margin-bottom: 2rem; }}
    td   {{ padding: .2rem 1.5rem .2rem 0; vertical-align: top; }}
    td:first-child {{ color: #888; white-space: nowrap; }}
    pre  {{ {fg_css}; line-height: 1.1; font-size: .7rem; white-space: pre; }}
    footer {{ margin-top: 2rem; color: #444; font-size: .8rem; }}
  </style>
</head>
<body>
  <h1>{html.escape(char.name)}</h1>
  <table>
    <tr><td>ID</td><td>{char.id}</td></tr>
    <tr><td>Status</td><td>{html.escape(char.status)}</td></tr>
    <tr><td>Species</td><td>{html.escape(char.species)}</td></tr>
    <tr><td>Gender</td><td>{html.escape(char.gender)}</td></tr>
    <tr><td>Origin</td><td>{html.escape(char.origin)}</td></tr>
    <tr><td>Location</td><td>{html.escape(char.location)}</td></tr>
    <tr><td>Episodes</td><td>{char.episode_count}</td></tr>
  </table>
  <pre>{escaped_art}</pre>
  <footer>Generated by Rick Terminal &mdash; {char.url}</footer>
</body>
</html>
"""
    path.write_text(html_content, encoding="utf-8")
    return path
